# Generated by Django 3.2.3 on 2021-09-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_img',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
