# Generated by Django 3.2.3 on 2021-09-29 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productmodel_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='author',
        ),
    ]
