# Generated by Django 3.2.3 on 2021-08-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoreact', '0002_alter_user_phonenum'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_table',
        ),
    ]
